import * as Linking from 'expo-linking';

/**
 * Builds the invitation link for an invite code.
 *
 * `Linking.createURL` resolves to the app's own scheme (`split://join/AB12CD`)
 * in a build, and to the development URL under Expo Go, so the same link works
 * everywhere without anything being hardcoded.
 *
 * Codes themselves are generated by the database with a CSPRNG; nothing here
 * invents one.
 */
export function buildInvitationLink(code: string) {
  return Linking.createURL(`/join/${code}`);
}

/**
 * The message that gets sent.
 *
 * The code comes first and the link second, deliberately: the link uses the
 * app's own scheme, which messaging apps render as dead text. Someone who
 * already has Split can always fall back to typing the code into "Join a
 * Table", so the part that works has to be the part they read first.
 */
export function buildInvitationMessage(code: string) {
  return [
    'Join my table on Split 🍽️',
    `Table code: ${code}`,
    'Open Split and tap "Join a Table", or use this link:',
    buildInvitationLink(code),
  ].join('\n');
}
