import * as Linking from 'expo-linking';

/**
 * Builds the invitation link for an invite code.
 *
 * `Linking.createURL` resolves to the app's own scheme (`split://join/AB12CD`)
 * in a build, and to the development URL under Expo Go, so the same link works
 * everywhere without anything being hardcoded.
 *
 * Codes themselves are generated by the database with a CSPRNG; nothing here
 * invents one.
 */
export function buildInvitationLink(code: string) {
  return Linking.createURL(`/join/${code}`);
}

export function buildInvitationMessage(code: string) {
  return `Join my table on Split 🍽️\nTap to join: ${buildInvitationLink(code)}`;
}
